# When making changes to this file update requirements.txt also !!
# Usage: conda -v env update -n lektrix --file environment.yml; pre-commit run --all-files

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - pip
  - pre-commit
  - pyarrow
  - pytz
  - requests
  - scipy
