# When making changes to this file update requirements.txt also !!
# Usage:
# conda -v env update --file environment.yml; pre-commit run --all-files; pycheck

name: volvopy

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - pip

  # imported deps
  - pytz=2024.1
  - requests=2.32.3

  # dev deps
  - jupyterlab
  - pandas
  - pylint>=3.0.2
  - pipdeptree
  - pre-commit
  - pyarrow
  - scipy
